import {
  CiBoxList,
  CiCalculator2,
  CiCalendarDate,
  CiClock1,
  CiDeliveryTruck,
  CiDiscount1,
  CiLock,
  CiMedicalClipboard,
  CiRollingSuitcase,
  CiShoppingBasket,
  CiText,
  CiTimer,
  CiUser,
} from "react-icons/ci";
import {
  FaBoxes,
  FaCalendarCheck,
  FaCalendarPlus,
  FaCalendarTimes,
  FaCalendarWeek,
  FaCheckCircle,
  FaClipboardCheck,
  FaCogs,
  FaList,
  FaPlayCircle,
  FaRegFutbol,
  FaTimesCircle,
  FaTools,
  FaTruckLoading,
  FaUser,
} from "react-icons/fa";

export const resources = [
  {
    path: "appointments",
    dataSource: "https://ehs-server.onrender.com/appointments",
    icon: CiRollingSuitcase,
    sidePanel: false,
    type: "crudTab",
    add: false,
    view: true,
    edit: false,
    update: false,
    delete: false,
    menu: "user",
    tabs: [
      { name: "scheduled", Icon: FaCalendarPlus },
      { name: "confirmed", Icon: FaCalendarCheck },
      { name: "completed", Icon: FaCalendarWeek },
      { name: "cancelled", Icon: FaCalendarTimes },
    ],
    schema: [
      { name: "patientName", title: "Patient Name", type: "text" },
      { name: "doctorName", title: "Doctor Name", type: "text" },
      {
        name: "status",
        title: "Status",
        sidePanel: false,
        type: "select",
        options: [
          { label: "Scheduled", value: "scheduled" },
          { label: "Confirmed", value: "confirmed" },
          { label: "Completed", value: "completed" },
          { label: "Cancelled", value: "cancelled" },
        ],
      },
      { name: "appointmentDate", title: "Appointment Date", type: "date" },
      { name: "appointmentTime", title: "Appointment Time", type: "time" },
    ],
  },
  {
    path: "matches",
    dataSource: "https://ehs-server.onrender.com/football-matches",
    icon: FaRegFutbol,
    sidePanel: false,
    type: "crudTab",
    add: false,
    view: true,
    edit: false,
    update: false,
    delete: false,
    menu: "user",
    tabs: [
      { name: "upcoming", Icon: FaCalendarPlus },
      { name: "live", Icon: FaPlayCircle },
      { name: "completed", Icon: FaCheckCircle },
      { name: "cancelled", Icon: FaTimesCircle },
    ],
    schema: [
      { name: "homeTeam", title: "Home Team", type: "text" },
      { name: "awayTeam", title: "Away Team", type: "text" },
      { name: "venue", title: "Venue", type: "text" },
      { name: "matchDate", title: "Match Date", type: "date" },
      { name: "matchTime", title: "Match Time", type: "time" },
      {
        name: "status",
        title: "Status",
        sidePanel: false,
        type: "select",
        options: [
          { label: "Upcoming", value: "upcoming" },
          { label: "Live", value: "live" },
          { label: "Completed", value: "completed" },
          { label: "Cancelled", value: "cancelled" },
        ],
      },
    ],
  },
  {
    path: "deliveries",
    dataSource: "https://ehs-server.onrender.com/deliveries",
    icon: CiDeliveryTruck,
    sidePanel: false,
    type: "crudTab",
    add: false,
    view: false,
    edit: false,
    update: false,
    delete: false,
    menu: "settings",
    tabs: [
      { name: "pending", Icon: CiTimer },
      { name: "in-transit", Icon: FaTruckLoading },
      { name: "delivered", Icon: FaClipboardCheck },
      { name: "cancelled", Icon: FaTimesCircle },
    ],
    schema: [
      { name: "recipientName", title: "Recipient Name", type: "text" },
      { name: "deliveryAddress", title: "Delivery Address", type: "text" },
      {
        name: "status",
        title: "Status",
        sidePanel: false,
        type: "select",
        options: [
          { label: "Pending", value: "pending" },
          { label: "In Transit", value: "in-transit" },
          { label: "Delivered", value: "delivered" },
          { label: "Cancelled", value: "cancelled" },
        ],
      },
      { name: "deliveryDate", title: "Delivery Date", type: "date" },
      { name: "deliveryTime", title: "Delivery Time", type: "time" },
    ],
  },
  {
    path: "users",
    dataSource: "https://ehs-server.onrender.com/users",
    icon: CiUser,
    sidePanel: false,
    type: "crud",
    add: true,
    view: true,
    edit: true,
    update: true,
    delete: true,
    menu: "user",
    menuIcon: FaList,
    schema: [
      { name: "name", title: "Name", type: "text" },
      { name: "email", title: "Email", type: "text" },
      { name: "password", title: "Password", type: "password" },
      {
        name: "role",
        title: "Role",
        sidePanel: false,
        type: "select",
        options: [
          { label: "Administrator", value: "admin" },
          { label: "Customer", value: "buyer" },
          { label: "Seller", value: "seller" },
        ],
      },
    ],
  },

  {
    path: "categories",
    dataSource: "https://ehs-server.onrender.com/categories",
    icon: CiBoxList,
    sidePanel: false,
    type: "crud",
    add: true,
    view: true,
    edit: true,
    update: true,
    delete: true,
    menu: "dashboard",
    menuIcon: FaList,
    schema: [
      { name: "name", title: "Name", type: "text" },
      { name: "description", title: "Description", type: "textarea" },
      { name: "createdAt", title: "Created At", type: "date" },
      { name: "updatedAt", title: "Updated At", type: "date" },
    ],
  },

  // Resource 6: Customers
  {
    path: "customers",
    dataSource: "https://ehs-server.onrender.com/customers",
    icon: CiUser,
    sidePanel: false,
    type: "crud",
    add: true,
    view: true,
    edit: true,
    update: true,
    delete: true,
    menu: "dashboard",
    menuIcon: FaList,
    schema: [
      { name: "name", title: "Name", type: "text" },
      { name: "email", title: "Email", type: "email" },
      { name: "phone", title: "Phone", type: "tel" },
      { name: "createdAt", title: "Created At", type: "date" },
      { name: "updatedAt", title: "Updated At", type: "date" },
    ],
  },

  // Resource 8: Employees
  {
    path: "employees",
    dataSource: "https://ehs-server.onrender.com/employees",
    icon: CiUser,
    sidePanel: false,
    type: "crud",
    add: true,
    view: true,
    edit: true,
    update: true,
    delete: true,
    menu: "dashboard",
    menuIcon: FaList,
    schema: [
      { name: "name", title: "Name", type: "text" },
      { name: "email", title: "Email", type: "email" },
      {
        name: "role",
        title: "Role",
        sidePanel: false,
        type: "select",
        options: [
          { label: "Logistics", value: "logistics" },
          { label: "Administrator", value: "administrator" },
          { label: "Sales", value: "sales" },
          { label: "Marketing", value: "marketing" },
          { label: "Accounting", value: "accounting" },
        ],
      },
      { name: "salary", title: "Salary", type: "number" },
      { name: "hireDate", title: "Hire Date", type: "date" },
    ],
  },

  {
    path: "projects",
    dataSource: "https://ehs-server.onrender.com/projects",
    icon: CiRollingSuitcase,
    sidePanel: true,
    type: "crud",
    add: true,
    view: false,
    edit: false,
    update: true,
    delete: true,
    menu: "settings",
    menuIcon: FaCogs,
    schema: [
      { name: "name", title: "Name", type: "text" },
      { name: "description", title: "Description", type: "textarea" },
      { name: "startDate", title: "Start Date", type: "date" },
      { name: "endDate", title: "End Date", type: "date" },
    ],
  },
  {
    path: "tasks",
    dataSource: "https://ehs-server.onrender.com/tasks",
    icon: CiMedicalClipboard,
    sidePanel: false,
    type: "crudGrid",
    add: true,
    view: true,
    edit: true,
    update: true,
    delete: true,
    menu: "settings",
    menuIcon: FaCogs,

    schema: [
      { name: "name", title: "Name", type: "text" },
      { name: "description", title: "Description", type: "textarea" },
    ],
  },
  {
    path: "events",
    dataSource: "https://ehs-server.onrender.com/events",
    icon: CiCalendarDate,
    sidePanel: false,
    type: "crud",
    add: true,
    view: true,
    edit: true,
    update: true,
    delete: true,
    menu: "settings",
    menuIcon: FaCogs,
    schema: [
      { name: "name", title: "Event Name", type: "text" },
      { name: "location", title: "Location", type: "text" },
      { name: "date", title: "Event Date", type: "date" },
      { name: "description", title: "Description", type: "richtextarea" },
    ],
  },
  {
    path: "orders",
    dataSource: "https://ehs-server.onrender.com/orders",
    icon: CiShoppingBasket,
    sidePanel: false,
    type: "crudGrid",
    add: true,
    view: true,
    edit: true,
    update: true,
    delete: true,
    menu: "utils",
    menuIcon: FaTools,
    schema: [
      { name: "orderNumber", title: "Order Number", type: "text" },
      { name: "customerName", title: "Customer Name", type: "text" },
      { name: "totalAmount", title: "Total Amount", type: "number" },
    ],
  },
  {
    path: "blog-posts",
    dataSource: "https://ehs-server.onrender.com/blog-posts",
    icon: CiText,
    sidePanel: false,
    type: "crud",
    add: true,
    view: true,
    edit: true,
    update: true,
    delete: true,
    menu: "utils",
    menuIcon: FaTools,
    schema: [
      { name: "title", title: "Title", type: "text" },
      { name: "content", title: "Content", type: "richtextarea" },
      { name: "author", title: "Author", type: "text" },
      { name: "date", title: "Publication Date", type: "time" },
      { name: "thumbnail", title: "Thumbnail", type: "file" },
    ],
  },
  {
    path: "profile",
    dataSource: "https://ehs-server.onrender.com/profile",
    icon: CiUser,
    sidePanel: false,
    type: "singleton",
    add: true,
    view: true,
    edit: true,
    update: true,
    delete: true,
    menu: "account",
    schema: [
      { name: "name", title: "Name", type: "text" },
      { name: "email", title: "Email", type: "email" },
      { name: "phone", title: "Phone", type: "text" },
      { name: "address", title: "Address", type: "textarea" },
      { name: "postalCode", title: "Postal Code", type: "text" },
      { name: "zipCode", title: "Zip Code", type: "text" },
      {
        name: "country",
        title: "Country",
        sidePanel: false,
        type: "select",
        options: [
          { label: "Algeria", value: "Algeria" },
          { label: "Morocco", value: "Morocco" },
          { label: "Tunisia", value: "Tunisia" },
          { label: "Egypt", value: "Egypt" },
          { label: "Sudan", value: "Sudan" },
          { label: "Libya", value: "Libya" },
          { label: "Djibouti", value: "Djibouti" },
          { label: "Somalia", value: "Somalia" },
          { label: "Kenya", value: "Kenya" },
          { label: "Ethiopia", value: "Ethiopia" },
          { label: "Seychelles", value: "Seychelles" },
          { label: "Senegal", value: "Senegal" },
          { label: "Mauritania", value: "Mauritania" },
          { label: "Mozambique", value: "Mozambique" },
        ],
      },
    ],
  },
];
